# Generated by Django 4.1.4 on 2023-06-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geopricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geopricingtiers',
            name='percentage',
            field=models.FloatField(default=0),
        ),
    ]
