# Generated by Django 4.1.4 on 2023-06-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geopricing', '0002_alter_geopricingtiers_percentage'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='geolocations',
            constraint=models.UniqueConstraint(fields=('country', 'currency'), name='geolocation_country_currency_constraint_unique'),
        ),
    ]
