# Generated by Django 4.1.4 on 2023-03-12 11:02

import apps.status.mixins
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='is_primary_exchange_rate_currency',
            field=apps.status.mixins.AtMostOneBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='currency',
            name='is_primary_store_currency',
            field=apps.status.mixins.AtMostOneBooleanField(default=False),
        ),
    ]
