# Generated by Django 4.1.4 on 2023-02-18 12:58

import apps.courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_qna_qnareplys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.UUIDField(default=apps.courses.models.courses_code, editable=False, unique=True),
        ),
    ]
