# Generated by Django 4.1.4 on 2023-02-18 13:10

import apps.courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(default=apps.courses.models.courses_code, editable=False, max_length=50, null=True),
        ),
    ]
