# Generated by Django 4.1.4 on 2023-02-21 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0006_alter_course_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursereview',
            name='reports',
        ),
        migrations.CreateModel(
            name='ReportedCourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('issue', models.CharField(max_length=200)),
                ('description', models.TextField(default='')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='courses.coursereview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reported_course_reviews',
            },
        ),
    ]
