# Generated by Django 4.1.4 on 2023-03-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('Draft', 'Status Draft'), ('Published', 'Status Published'), ('Rejected', 'Status Rejected'), ('In Review', 'Status Inreview'), ('UnListed', 'Status Unlisted')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='type',
            field=models.CharField(blank=True, choices=[('Video', 'Video'), ('Article', 'Article')], max_length=10, null=True),
        ),
    ]
