# Generated by Django 4.1.4 on 2023-03-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_course_status_alter_lecture_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsectionprogress',
            name='watched_duration',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
