# Generated by Django 4.1.4 on 2023-03-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_courseinreviewfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='preview',
            field=models.BooleanField(default=False),
        ),
    ]
