# Generated by Django 4.1.4 on 2023-03-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_subsectionprogress_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinreviewfeedback',
            name='unread',
            field=models.BooleanField(default=True),
        ),
    ]
