# Generated by Django 4.1.4 on 2023-03-21 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_courseinreviewfeedback_unread'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='subsection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qna', to='courses.subsection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qna',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
