# Generated by Django 4.1.4 on 2023-03-21 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_qna_subsection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qna',
            old_name='required',
            new_name='approved',
        ),
    ]
