# Generated by Django 4.1.4 on 2023-03-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_rename_required_qna_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='type',
            field=models.CharField(choices=[('Note', 'Note'), ('Highlight', 'Highlight')], default='Note', max_length=10),
        ),
    ]
