# Generated by Django 4.1.4 on 2023-03-22 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0019_remove_qna_course_qna_user_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='upvoted_users',
            field=models.ManyToManyField(blank=True, related_name='upvoted_qna', to='courses.course'),
        ),
        migrations.AddField(
            model_name='qnareplys',
            name='upvoted_users',
            field=models.ManyToManyField(blank=True, related_name='upvoted_qna_reply', to=settings.AUTH_USER_MODEL),
        ),
    ]
