# Generated by Django 4.1.4 on 2023-03-22 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0020_qna_upvoted_users_qnareplys_upvoted_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='upvoted_users',
            field=models.ManyToManyField(blank=True, related_name='upvoted_qna', to=settings.AUTH_USER_MODEL),
        ),
    ]
