# Generated by Django 4.1.4 on 2023-03-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_alter_lecture_video_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='video_info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
