# Generated by Django 4.1.4 on 2023-03-27 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_alter_lecture_video_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinreviewfeedback',
            name='quiz_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_question_feedbacks', to='courses.quizquestion'),
        ),
        migrations.AlterField(
            model_name='courseinreviewfeedback',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_section_feedbacks', to='courses.section'),
        ),
        migrations.AlterField(
            model_name='courseinreviewfeedback',
            name='subsection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_subsection_feedbacks', to='courses.subsection'),
        ),
    ]
