# Generated by Django 4.1.4 on 2023-04-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_alter_courseinreviewfeedback_type_reportedqnareply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinreviewfeedback',
            name='type_value',
            field=models.TextField(blank=True),
        ),
    ]
