# Generated by Django 4.1.4 on 2023-04-16 07:35

import apps.courses.models.lectures
import core.store.storage_backends
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0027_alter_course_image_alter_course_promo_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('type', models.CharField(choices=[('title', 'Title'), ('subtitle', 'Subtitle'), ('desc', 'Detail'), ('image', 'Image'), ('promo_video', 'Promo Video'), ('topics', 'Topics'), ('description', 'Description'), ('skill_level', 'Skill Level'), ('category', 'Category'), ('subcategory', 'Subcategory'), ('language', 'Language'), ('objectives', 'Objectives'), ('requirements', 'Requirements'), ('video_info', 'Video Thumbnail'), ('sections', 'Section'), ('subsections', 'Subsection'), ('questions', 'Quiz Question')], max_length=20)),
                ('message', models.TextField()),
                ('required', models.BooleanField(default=False)),
                ('current_value', models.TextField(blank=True)),
                ('index', models.IntegerField(default=0)),
                ('unread', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inreview_feedbacks', to='courses.course')),
                ('quiz_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_question_feedbacks', to='courses.quizquestion')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_section_feedbacks', to='courses.section')),
                ('subsection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_subsection_feedbacks', to='courses.subsection')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_inreview_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_change_history',
            },
        ),
        migrations.RemoveField(
            model_name='note',
            name='position',
        ),
        migrations.AddField(
            model_name='note',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(height_field='height', storage=core.store.storage_backends.PrivateMediaStorage(), upload_to=apps.courses.models.lectures.course_lecture_article, width_field='width'),
        ),
        migrations.AlterField(
            model_name='lectureresource',
            name='file',
            field=models.FileField(storage=core.store.storage_backends.PrivateMediaStorage(), upload_to=apps.courses.models.lectures.course_lecture_resources_media),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='CourseInReviewFeedback',
        ),
    ]
