# Generated by Django 4.1.4 on 2023-04-28 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_coursechangehistory_remove_note_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursechangehistory',
            options={'verbose_name_plural': 'Course Feedback/Change History'},
        ),
    ]
