# Generated by Django 4.1.4 on 2023-05-04 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_alter_coursechangehistory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='learners',
        ),
        migrations.RemoveField(
            model_name='course',
            name='objectives',
        ),
        migrations.RemoveField(
            model_name='course',
            name='requirements',
        ),
        migrations.AlterField(
            model_name='coursechangehistory',
            name='type',
            field=models.CharField(choices=[('title', 'Title'), ('subtitle', 'Subtitle'), ('desc', 'Detail'), ('image', 'Image'), ('promo_video', 'Promo Video'), ('topics', 'Topics'), ('description', 'Description'), ('skill_level', 'Skill Level'), ('category', 'Category'), ('subcategory', 'Subcategory'), ('language', 'Language'), ('objectives', 'Objectives'), ('requirements', 'Requirements'), ('learners', 'Learnings'), ('video_info', 'Video Thumbnail'), ('sections', 'Section'), ('subsections', 'Subsection'), ('questions', 'Quiz Question')], max_length=20),
        ),
        migrations.CreateModel(
            name='CourseRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('content', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_requirements', to='courses.course')),
            ],
            options={
                'db_table': 'course_requirements',
            },
        ),
        migrations.CreateModel(
            name='CourseObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('content', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_objectives', to='courses.course')),
            ],
            options={
                'db_table': 'course_objectives',
            },
        ),
        migrations.CreateModel(
            name='CourseLearner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('content', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_learners', to='courses.course')),
            ],
            options={
                'db_table': 'course_learners',
            },
        ),
    ]
