# Generated by Django 4.1.4 on 2023-05-04 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_remove_course_learners_remove_course_objectives_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursechangehistory',
            old_name='index',
            new_name='intended_learners',
        ),
    ]
