# Generated by Django 4.1.4 on 2023-05-08 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_coursechangehistory_assignment_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursechangehistory',
            name='subsection',
        ),
        migrations.AddField(
            model_name='coursechangehistory',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_lecture_feedbacks', to='courses.lecture'),
        ),
        migrations.AlterField(
            model_name='coursechangehistory',
            name='assignment_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_assignment_feedbacks', to='courses.assignmentquestion'),
        ),
        migrations.AlterField(
            model_name='coursechangehistory',
            name='quiz_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_quiz_feedbacks', to='courses.quizquestion'),
        ),
        migrations.AlterField(
            model_name='coursechangehistory',
            name='type',
            field=models.CharField(choices=[('title', 'Title'), ('subtitle', 'Subtitle'), ('desc', 'Detail'), ('image', 'Image'), ('promo_video', 'Promo Video'), ('topics', 'Topics'), ('description', 'Description'), ('skill_level', 'Skill Level'), ('category', 'Category'), ('subcategory', 'Subcategory'), ('language', 'Language'), ('objectives', 'Objectives'), ('requirements', 'Requirements'), ('learners', 'Learnings'), ('video_info', 'Video Thumbnail'), ('section', 'Section'), ('lecture', 'Lecture'), ('quiz_question', 'Quiz Question'), ('assignment_question', 'Assignment Question')], max_length=20),
        ),
    ]
