# Generated by Django 4.1.4 on 2023-05-08 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_remove_coursechangehistory_subsection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursechangehistory',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_assignment_feedbacks', to='courses.assignment'),
        ),
        migrations.AddField(
            model_name='coursechangehistory',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_quiz_feedbacks', to='courses.quiz'),
        ),
        migrations.AlterField(
            model_name='coursechangehistory',
            name='assignment_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_aq_feedbacks', to='courses.assignmentquestion'),
        ),
        migrations.AlterField(
            model_name='coursechangehistory',
            name='quiz_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_quizq_feedbacks', to='courses.quizquestion'),
        ),
    ]
