# Generated by Django 4.1.4 on 2023-05-08 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_coursechangehistory_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursechangehistory',
            name='pricing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_price_feedbacks', to='courses.courseprice'),
        ),
        migrations.AlterField(
            model_name='coursechangehistory',
            name='type',
            field=models.CharField(choices=[('title', 'Title'), ('subtitle', 'Subtitle'), ('desc', 'Detail'), ('image', 'Image'), ('promo_video', 'Promo Video'), ('topics', 'Topics'), ('description', 'Description'), ('skill_level', 'Skill Level'), ('category', 'Category'), ('subcategory', 'Subcategory'), ('language', 'Language'), ('objectives', 'Objectives'), ('requirements', 'Requirements'), ('learners', 'Learnings'), ('video_info', 'Video Thumbnail'), ('section', 'Section'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('lecture', 'Lecture'), ('quiz_question', 'Quiz Question'), ('assignment_question', 'Assignment Question'), ('pricing', 'Pricing')], max_length=20),
        ),
    ]
