# Generated by Django 4.1.4 on 2023-05-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_coursechangehistory_pricing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursechangehistory',
            name='current_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
