# Generated by Django 4.1.4 on 2023-02-05 17:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCoupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('discount', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('expiration_date', models.DateTimeField(verbose_name='Expiration date')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active?')),
                ('times_used', models.IntegerField(default=0, editable=False, verbose_name='Times used')),
                ('max_uses', models.BigIntegerField(default=1, verbose_name='Maximum uses')),
            ],
            options={
                'verbose_name_plural': 'Discount Coupons',
                'db_table': 'discount_coupons',
            },
        ),
        migrations.CreateModel(
            name='CourseDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active?')),
                ('times_used', models.IntegerField(default=0, editable=False, verbose_name='Times used')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupons.discountcoupons', verbose_name='Coupon')),
            ],
            options={
                'verbose_name_plural': 'Course Discount Coupons',
                'db_table': 'course_discount_coupons',
            },
        ),
    ]
