# Generated by Django 4.1.4 on 2023-02-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_refundrequest_transaction'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transactionpayout',
            constraint=models.UniqueConstraint(fields=('payout', 'transaction'), name='per_transaction_payout_constraint'),
        ),
    ]
