# Generated by Django 4.1.4 on 2023-02-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transactionpayout_per_transaction_payout_constraint'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='holdtransaction',
            constraint=models.UniqueConstraint(fields=('status', 'transaction'), name='hold_transaction_status_constraint'),
        ),
        migrations.AddConstraint(
            model_name='payoutdirecttransition',
            constraint=models.UniqueConstraint(fields=('status', 'payout'), name='direct_payout_status_constraint'),
        ),
    ]
