# Generated by Django 4.1.4 on 2023-03-03 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_transactions_gateway_charge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='gateway_transaction_id',
            new_name='payment_transaction_id',
        ),
        migrations.RemoveField(
            model_name='paymenttype',
            name='gateway_charge',
        ),
    ]
