# Generated by Django 4.1.4 on 2023-02-05 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('period', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Current', 'Current')], default='Current', max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Statement',
                'verbose_name_plural': 'Statements',
                'db_table': 'statements',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='StatementTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('transaction_detail', models.JSONField(default=dict)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='statements.statement')),
            ],
            options={
                'verbose_name': 'Transaction Statement',
                'verbose_name_plural': 'Transaction Statements',
                'db_table': 'statements_transaction',
                'ordering': ['-date_created'],
            },
        ),
    ]
