# Generated by Django 4.1.4 on 2023-02-07 10:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclass',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=True),
        ),
    ]
