# Generated by Django 4.1.4 on 2023-02-07 10:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userclass_id_userclass_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclass',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
