# Generated by Django 4.1.4 on 2023-02-18 12:56

import uuid
import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_order_refund_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclass',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
