# Generated by Django 4.1.4 on 2023-02-18 13:10

import uuid
import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userclass_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclass',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
