# Generated by Django 4.1.4 on 2023-02-22 18:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userclass_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
