# Generated by Django 4.1.4 on 2023-03-03 09:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclass',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
