# Generated by Django 4.1.4 on 2023-03-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userclass_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclass',
            name='archived',
            field=models.BooleanField(default=False, help_text='less frequently used'),
        ),
    ]
