# Generated by Django 4.1.4 on 2023-04-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_userclass_certificate_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclass',
            name='certificate_number',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
