# Generated by Django 4.1.4 on 2023-05-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_instructor_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='instructor_consent',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
