# Generated by Django 4.1.4 on 2023-05-04 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_instructor_instructor_consent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='instructor_consent',
        ),
    ]
