# Generated by Django 4.1.4 on 2023-05-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_instructor_instructor_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='public_courses',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='public_profile',
            field=models.BooleanField(default=True),
        ),
    ]
