# Generated by Django 4.1.4 on 2023-05-23 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0006_alter_instructorgroup_unique_together_and_more'),
        ('users', '0022_alter_notificationsettings_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shares.instructorgroup'),
        ),
    ]
