# Generated by Django 4.1.4 on 2023-02-22 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shares', '0003_shareprices_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorgroup',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sharegroup', to=settings.AUTH_USER_MODEL),
        ),
    ]
