# Generated by Django 4.1.4 on 2023-02-22 18:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0004_alter_instructorgroup_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareprices',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
