# Generated by Django 4.1.4 on 2023-05-23 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0005_alter_shareprices_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instructorgroup',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='shareprices',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='instructorgroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shareprices',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shares.instructorgroup'),
        ),
        migrations.AlterField(
            model_name='instructorgroup',
            name='group_name',
            field=models.CharField(default='default', max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='shareprices',
            unique_together={('share_types', 'group')},
        ),
        migrations.RemoveField(
            model_name='instructorgroup',
            name='user',
        ),
    ]
