# Generated by Django 4.1.4 on 2023-02-05 17:55

import apps.countries.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('two_letter_iso_code', models.CharField(max_length=2, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]*$', 'Only Alphabetic characters are allowed.'), django.core.validators.MinLengthValidator(2)])),
                ('three_letter_iso_code', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]*$', 'Only Alphabetic characters are allowed.'), django.core.validators.MinLengthValidator(3)])),
                ('numeric_iso_code', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only Numeric characters are allowed.'), django.core.validators.MinLengthValidator(3)])),
                ('subject_to_vat', models.BooleanField(default=False)),
                ('allow_billing', models.BooleanField(default=False)),
                ('sort_number', models.PositiveIntegerField(default=apps.countries.models.auto_increase, unique=True)),
            ],
            options={
                'db_table': 'countries',
                'ordering': ['sort_number'],
            },
        ),
    ]
