# Generated by Django 4.1.4 on 2023-04-09 11:05

import apps.notifications.models
import core.store.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='template_image',
            field=models.ImageField(blank=True, null=True, storage=core.store.storage_backends.PrivateMediaStorage(), upload_to=apps.notifications.models.notification_template_image),
        ),
    ]
